[#100] PC 리스폰 구현
hwi-middle/2024-CKGraduationWork pull request #103
Opened 2024-04-19 14:47 UTC by thejae-u

2024-04-20 15:01 UTC, hwi-middle requested changes
수고 많으셨습니다. 세이브 포인트 정보를 내부적으로 저장하는 로직에 대한 의견이 있어서 해당 내용 달아두었으니 확인부탁드립니다!

2024-04-20 15:11 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Camera/CameraController.cs
> +        AimingCamera.m_YAxis.Value = 0.5f;
플레이어나 맵을 배치 할 때 플레이어가 보고있는 방향에 따라 `cinemachine`의 `X Offset`의 최초 값이 0이라 할 때 이전에 시연 씬을 제작할 때 보았던 카메라가 플레이어의 앞을 보여주는 현상이 있게 됩니다. 그렇기 때문에 플레이어의 방향으로 카메라의 `X Offset`을 변경하여 주는 함수입니다.

2024-04-20 15:12 UTC, thejae-u commented on Assets/_MyAssets/Scripts/CheckPoint/CheckPointData.cs
> +    public static bool IsSameScene => SceneManager.GetActiveScene().name == _currentSceneName;
확인했습니다. 변경조치 하겠습니다.

2024-04-20 15:12 UTC, thejae-u commented on Assets/_MyAssets/Scripts/CheckPoint/CheckPointData.cs
> +    }
이 코멘트로 인해 더욱 간단하게 구현이 가능 해 질 것같다는 생각이 드는 것 같습니다. 로직 변경하도록 하겠습니다.

2024-04-20 15:12 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Player/AnimationUpdater.cs
> +        }
이후에 애니메이션 클립에 대한 `Duration`을 동적으로 꺼내 쓰기 위해 만들어 둔 필드입니다.
후에 사용하게 될 경우 다른 방식으로 사용 할 수 있도록 연구하도록 하겠습니다.
현재 브랜치에서는 삭제 조지 하겠습니다.

2024-04-20 15:12 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Player/Player.cs
> +        }
확인했습니다. 너무 위험한 코드를 그냥 노출시키고 있었습니다..

2024-04-20 17:27 UTC, thejae-u commented
Review 주신 점 참고하여 수정 조치하였습니다.
`PlayerPrefs`로 관리하는 로직으로 구현하였습니다.

2024-04-21 09:36 UTC, hwi-middle requested changes

2024-04-21 09:37 UTC, hwi-middle approved these changes

2024-04-21 09:37 UTC, merged