[#104] 상호작용 기능 개선
hwi-middle/2024-CKGraduationWork pull request #105
Opened 2024-04-21 14:33 UTC by thejae-u

# 상호작용 기능에 대한 개선 작업을 하였습니다.

### 변경 내용
- 기존에 숨기 기능으로만 작용했던 `F` 키의 기능이 아이템 줍기까지 확장되었습니다.

### 구현 내용
- 일정 범위 내에서 화면 상으로 가장 중앙에 위치한 오브젝트를 타겟으로 하여 UI를 띄워주도록  구현하였습니다.
- 오브젝트와 플레이어 사이에 무언가 방해하는 것이 있다면 띄우지 않도록 하였습니다.

resolved #104 

https://github.com/hwi-middle/2024-CKGraduationWork/assets/31125543/7fda28ac-e759-4e95-bf20-2f4844b4c5cf

2024-04-22 10:42 UTC, hwi-middle requested changes

2024-04-22 10:42 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Interaction/InteractionController.cs
> +    private Dictionary<int, InteractionObject> _interactionObjects = new();
`_interactableObjects`

2024-04-22 10:42 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Interaction/InteractionController.cs
> +        foreach (var data in _interactionObjects)
이 반복문이 개선될 여지가 많아보입니다. `isOnlyOne`에 대한 처리를 중심으로 더 줄일 수 있을지 고민해주셨으면 좋겠습니다!

2024-04-22 11:27 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Interaction/ItemHandler.cs
> +        if (other.gameObject.CompareTag("Player") || other.gameObject.CompareTag("InteractionTriggerZone"))
맵에 배치된 아이템에 `ItemHandler`를 붙였던 이유는 이전에 구현 과정에서 설계할 때 맵에 배치된 아이템을 그대로 들어서 사용 하도록 의도했었는데 방식이 바뀌면서 빼지 못했던 것 같습니다. 조금 더 정리 할 수 있도록 하겠습니다.

참고로 저 조건은 아이템이 날아가는 도중 맵에 배치 되어있는 상호작용 가능한 오브젝트의 TriggerZone에 닿으면 의도하지 않은 곳에서 사라지는 현상이 있어 추가하였습니다.

2024-04-22 11:50 UTC, thejae-u commented
Review 주신대로 수정하였습니다.
`isOnlyOne`에 대한 로직을 따로 빼고 반복문에서 수행하는 로직을 함수로 빼는 작업을 하였습니다.

2024-04-23 07:07 UTC, hwi-middle approved these changes

2024-04-23 07:10 UTC, merged