[#122] 팝업 창 및 게임 종료 구현
hwi-middle/2024-CKGraduationWork pull request #123
Opened 2024-05-07 09:04 UTC by thejae-u

###구현 내용
- 팝업창을 구현하였습니다.
- 게임 시작, 종료 전 팝업을 띄우도록 하였습니다.

### 변경 내용
- 기존에 ESC를 누르면 나오던 창이 옵션 창에서 Pause 창으로 변경됨에 따라 Pause창에서 Option창으로 전환 할 수 있도록 하였습니다.

### 참고 사항
- 팝업 창의 종류는 4가지로 각 `Info, Confirm, Warning, Error` 가 있습니다.
  - `Info` : 확인 버튼만 존재하며 유저에게 알릴 내용이 있을 때 사용합니다.
  - `Confirm` : 확인, 취소 버튼이 있으며 유저가 선택을 해야 할 때 사용합니다.
  - `Warning` : 확인, 취소 버튼이 있으며 취소 버튼은 Default가 `비어있음` 입니다. 경고 창으로 유저에게 주의를 주어야 할 때 사용합니다.
  - `Error` : 에러 창으로 게임에서 오류라고 판단 될 때 사용하며 게임을 강제 종료하는 로직입니다.

2024-05-10 14:12 UTC, hwi-middle requested changes
수고 많으셨습니다. 전반적으로 팝업을 띄우는 구조는 간편해보입니다. 유니티 에디터를 포함하여 여러 GUI 프로그래밍에서는 positive와 negative의 결과를 `bool`로 반환하여 if문에 바로 가져다쓰곤 하지만, 이것은 코드 흐름을 정지하고(blocking) 입력을 기다리는 형태이므로 게임에서 사용하기에는 어려울 것입니다.

이러한 관점에서 `Actoin<T>`을 사용한 코드는 훌륭하게 작동합니다. 또한, 단순히 팝업을 구현하는 것을 넘어 Scene에 팝업이 띄워져 있는지 확인하는 것과 같이 여러가지 유용한 방향을 고민해주신 점이 인상적입니다.

다만, 이번 review에서는 네이밍에 대한 부분이 유독 많이 걸렸습니다. 네이밍에 대한 지적은 이전부터 이어지고 있는데요. 쓴소리를 하지 않을 수 없는 대목입니다. 프로그래머에게 좋은 이름을 찾는 것은 대단히 중요한 '업무'입니다.

우스갯소리로 프로그래머가 가장 어려워하는 것이 이름짓기라고 하지요. 프로그래머는 그만큼 좋은 이름을 짓기 위해 치열하게 고민해야한다는 의미입니다. 강력한 어조로 말씀드리자면, 네이밍에 대해 깊은 고민을 하지 않는 것은 직무유기에 가깝다고 생각합니다. 저는 재우님이 좋은 프로그래머이자 함께 일 하고 싶은 동료임을 믿어 의심치 않습니다. 앞으로 네이밍에 대해서는 더 주의깊게 살펴봐주시길 바랍니다.

다시 한 번, 수고 많으셨습니다.

2024-05-10 14:12 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/UI/Popup/PopupHandler.cs
> +#endif
오류를 Handling할 때에도 Action을 받아서 처리하도록 해주시면 감사하겠습니다. 단순히 사용자에게 오류가 발생했음을 알리고 그대로 진행하도록 할 수도 있기 때문입니다.

2024-05-10 14:12 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/UI/Popup/PopupHandler.cs
> +        // Subscription Object
description입니다.

2024-05-11 13:21 UTC, thejae-u commented on Assets/_MyAssets/Scripts/UI/Popup/PopupHandler.cs
> +    public void FloatInfoPopup(Action<bool> action, string title, string description, string positive)
`Display`로 변경하였습니다.

2024-05-11 13:21 UTC, thejae-u commented on Assets/_MyAssets/Scripts/UI/Popup/PopupHandler.cs
> +    private TMP_Text _negativeButton;
해당 부분 각 `text` 를 추가하여 `_positiveText`, `_negativeText`로 변경하였습니다.

2024-05-11 13:21 UTC, thejae-u commented on Assets/_MyAssets/Scripts/SceneManagers/WorkSpace/WorkspaceSceneManager.cs
`WorkspaceSceneManager.cs`를 그 역할로 사용하려고 만들어 두긴 했습니다.

2024-05-11 13:21 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Utils/SceneManagerBase.cs
> +    private void AllocatePopupHandler()
`RequireComponent` 통해서 수정하였습니다.

2024-05-11 13:21 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Misc/PauseCanvasController.cs
> +        _quitButton.gameObject.SetActive(!SceneManagerBase.Instance.IsMainMenu);
해당 부분 말씀 해 주신대로 `SceneNames` 클래스를 통해 상수로 지정 및 적용하였습니다.
다만 `SceneManager.GetActiveScene().name`이 null을 반환하지 않기 때문에 `Equals`를 통해 적용하였습니다.

2024-05-11 13:21 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Misc/CursorVisibleUpdater.cs
> +public class CursorVisibleUpdater : Singleton<CursorVisibleUpdater>
`CursorLockModeUpdater`로 수정하였습니다.

2024-05-11 13:22 UTC, thejae-u commented on Assets/_MyAssets/Scripts/CheckPoint/CheckPointRootHandler.cs
> +    public bool IsCheckPointExist => PlayerPrefs.HasKey(_lastCheckPoint);
이어하기를 위해 작성 해 둔 코드인데 지금 보니 로직이 약간 안맞아 수정하였습니다.
추가로 명확한 이름이 아니어서 해석하시는데 어려움이 있었던 것 같습니다. 더 명확한 이름으로 수정하였습니다.

2024-05-11 13:22 UTC, thejae-u commented on Assets/_MyAssets/Scripts/UI/Popup/PopupHandler.cs
> +        _negativeButton.transform.parent.gameObject.SetActive(!string.IsNullOrEmpty(negative));
`Equals` 통해 수정하였습니다.

2024-05-11 13:22 UTC, thejae-u commented on Assets/_MyAssets/Scripts/UI/Popup/PopupHandler.cs
> +    private void SetPopupText(string title, string description, string positive, string negative)
`Display`라는 단어를 추가하여 좀 더 명확하게 하였습니다.
추가로 `negative` 에 Default parameter 적용하였습니다.

2024-05-11 13:22 UTC, thejae-u commented on Assets/_MyAssets/Scripts/UI/Popup/PopupHandler.cs
> +#endif
![image](https://github.com/hwi-middle/2024-CKGraduationWork/assets/31125543/fdef5fd4-4078-4497-adee-a6db706d1967)

이 부분의 의도는 이런 느낌의 에러 팝업창이었는데 이런 상황이 발생할 가능성이 없을 것 같아 바로 수정하였습니다.

2024-05-11 13:23 UTC, thejae-u commented
일부 네이밍 수정 요청 comment에는 추가적인 reply 없이 바로 수정하였습니다.

2024-05-11 15:12 UTC, hwi-middle requested changes
수고하셨습니다. 잘못 수정된 파일이 있는 것 같아 이 부분만 마지막으로 수정하고 머지합시다.

2024-05-11 15:12 UTC, hwi-middle commented on Assets/Editor/BehaviorTree/NodeView.uxml
> +    <ui:VisualElement name="node-isPositive" style="flex-grow: 1;" />
`state`를 `isPositive`로 replace하면서 이 부분도 변경된 것 같습니다.

2024-05-11 16:42 UTC, thejae-u commented on Assets/Editor/BehaviorTree/NodeView.uxml
> +    <ui:VisualElement name="node-isPositive" style="flex-grow: 1;" />
원상복구 하였습니다.

2024-05-12 06:37 UTC, merged

2024-05-12 06:37 UTC, hwi-middle commented
수정이 반영되지 않은 부분 1개 있어서 제가 수정하고 머지했습니다! 수고많았습니다 ^.^