[#124] 오디오 매니저 구현
hwi-middle/2024-CKGraduationWork pull request #125
Opened 2024-05-10 09:19 UTC by thejae-u

### 구현 내용
- 오디 매니저를 구현하였습니다.
- 재생, 중지, 일시정지 기능이 있으며 각 유형별로 함수가 존재합니다.
- 오디오 리소스를 `ScriptableObject`에 올리고 Generate 버튼을 누르면 해당하는 리소스의 이름을 Enum타입으로 만들어주는 기능을 구현하였습니다.

https://github.com/hwi-middle/2024-CKGraduationWork/assets/31125543/d27a050c-5859-4e41-bba0-09fb5a714ec2

2024-05-16 08:42 UTC, hwi-middle requested changes
수고하셨습니다. 구두로 협의한 내용까지 포함하여 수정해주시면 감사하겠습니다.

2024-05-16 08:42 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Audio/AudioObject.cs
> +    private EBgmAudioClipIndex _bgmClipIndex;
SFX도 되고, BGM도 되고 하다보니 필드부터 함수까지 애매한 구현이 많아졌습니다. 어차피 AudioObject가 Sfx이면서 Bgm일 수 없다면 클래스를 구분하는게 좋을 것 같습니다.

2024-05-16 08:42 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Audio/AudioPlayManager.cs
> +        GameObject bmgAudioObject = Instantiate(_audioObjectPrefab, transform);
bgm입니다.

2024-05-16 08:42 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Audio/AudioPlayManager.cs
> +    private Dictionary<int, AudioClip> _cachedBgmClips = new();
이쪽 `readonly` 키워드가 들어가면 좋겠습니다!

2024-05-16 08:42 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Audio/AudioPlayManager.cs
> +    private Dictionary<int, AudioClip> _cachedBgmClips = new();
여기는 Key가 int일 필요가 없어보입니다.

2024-05-16 08:42 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Audio/AudioPlayManager.cs
> +            _audioObjectPrefab = Resources.Load<GameObject>("Audio/AudioObject");
간단한 오브젝트라서 코드레벨에서 생성 후 `AddComponent`해줘도 될 것 같습니다.

2024-05-16 08:42 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Audio/AudioPlayManager.cs
> +        List<AudioClipInfo> clipInfoList = audioType == EAudioType.Bgm ? _audioClipData.bgmClipList : _audioClipData.sfxClipList;
switch문으로 바꿔주세요.

2024-05-16 08:42 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Data/AudioClipData.cs
> +    public int maxAudioObjectCount = 20;
pool의 capacity를 저장하는 느낌이 더 명확하면 좋겠습니다.

2024-05-16 14:05 UTC, thejae-u commented on Assets/_MyAssets/Data/EBgmAudioClipIndex.cs
이전부터 왜 안보이는가 했더니 인코딩 문제였군요... 해당 부분 수정하였습니다.

2024-05-16 14:06 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Utils/SceneManagerBase.cs
> +        }
`SoundManager` 풀링 방식 특성 상 자식 오브젝트가 생성되기에 `SceneManagerBase`의 하위보다는 별도의 오브젝트가 필요하다고 판단하여 Assertion 방식으로 수정하였습니다.

2024-05-16 14:06 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Audio/AudioObject.cs
> +    private void CheckSfxIsPlayingAndReturnObject()
수정된 네이밍 입니다.
`CheckNonLoopingSfxIsPlayingAndReturnObject`

2024-05-16 14:06 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Audio/AudioObject.cs
> +    private EBgmAudioClipIndex _bgmClipIndex;
클래스를 분리하여 `AudioObject`는 단순 구조가 되도록 수정하였습니다.

2024-05-16 14:06 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Audio/AudioPlayManager.cs
> +    private Dictionary<int, AudioClip> _cachedBgmClips = new();
적용하였습니다.

2024-05-16 14:06 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Audio/AudioPlayManager.cs
> +    private Dictionary<int, AudioClip> _cachedBgmClips = new();
Enum이 키가 되도록 수정하였습니다.

2024-05-16 14:06 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Audio/AudioPlayManager.cs
> +            _audioObjectPrefab = Resources.Load<GameObject>("Audio/AudioObject");
`AudioPlayManager` 의 Awake 에서 Bgm과 Sfx 각각 코드레벨 생성 하였습니다.

2024-05-16 14:08 UTC, thejae-u commented
코멘트 주신 부분 수정 완료하였습니다.

2024-05-17 07:42 UTC, hwi-middle approved these changes
LGTM, 수고하셨습니다.

2024-05-18 14:05 UTC, merged