[#126] 튜토리얼 팝업 구현
hwi-middle/2024-CKGraduationWork pull request #134
Opened 2024-05-14 10:52 UTC by thejae-u

### 구현 내용
- 기존 팝업 시스템 (#122) 을 이용하여 튜토리얼 팝업을 구현하였습니다.
- 레퍼런스 였던 젤다와 비슷하게 만들었으며 다음의 세 가지 조건을 만족합니다.
  - 함수를 호출하면 게임이 잠시 멈추고 팝업이 떠야함
  - Trigger에 닿으면 함수를 호출하거나, SceneManager에서 특정 조건 만족 시 호출하는 식으로 활용
  - 동영상을 재생할 수 있게 하고 그 아래에 제목과 내용 넣을 것

resolved #126 

https://github.com/hwi-middle/2024-CKGraduationWork/assets/31125543/514b4025-d126-4890-804c-94c59599909e

2024-05-16 09:07 UTC, hwi-middle requested changes
수고하셨습니다. 인코딩만 수정하면 될 것 같습니다.

2024-05-16 09:07 UTC, hwi-middle commented on Assets/Editor/TutorialVideoEnumGenerator.cs
> +        using TextWriter writer = new StreamWriter(PATH, false, Encoding.Unicode);
인코딩 수정합시다!

2024-05-16 11:07 UTC, thejae-u commented on Assets/Editor/TutorialVideoEnumGenerator.cs
> +        using TextWriter writer = new StreamWriter(PATH, false, Encoding.Unicode);
`UTF-8`로 수정 완료하였습니다.

2024-05-17 10:03 UTC, hwi-middle approved these changes
LGTM, 수고하셨습니다.

2024-05-18 14:07 UTC, merged