[#135] 큐브 돌리기 상호작용 초안 구현
hwi-middle/2024-CKGraduationWork pull request #137
Opened 2024-05-17 09:03 UTC by thejae-u

### 구현 내용
- 큐브 돌리기 상호작용에 대해서 기초 구현을 하였습니다.
- 큐브가 회전할 때의 동작을 조금 더 역동적으로 표현하였습니다.

### 참고 사항
- 기존의 상호작용을 토대로 구현하였습니다.
- 자세한 기획이 없어 키에 대해 설명합니다.
  - F : 상호작용 키
  - W, S : 큐브 선택 키 W는 위, S는 아래의 큐브로 옮김
  - A, D : 큐브 회전 키 A는 시계, D는 반시계 방향으로 큐브를 회전함

resolved #135 

https://github.com/hwi-middle/2024-CKGraduationWork/assets/31125543/4733e2ad-ce4d-42cc-84c0-d1688379752a

2024-05-20 09:30 UTC, hwi-middle requested changes
수고하셨습니다. 전반적으로 깔끔한 구현이었고요. 특히 EasingFunctions를 별도의 static 클래스로 빼둔 점은 훌륭합니다. 몇 가지 수정만 하면 바로 머지할 수 있을 것 같습니다.

2024-05-20 09:30 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Easing/EasingFunctions.cs
아주 좋은 구현입니다! 위치를 Scripts 폴더 내 Utils 쪽으로 옮겨주시면 감사하겠습니다 ^.^

2024-05-20 09:30 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Interaction/Cube/CubeRootHandler.cs
> +            float duration = EasingFunctions.EaseInOutBounce(alpha);
duration은 아닌 것 같고.. `easedAlpha` 어떨까요?

2024-05-20 09:30 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Interaction/Cube/CubeRootHandler.cs
> +    public void SelectNextCube()
Next랑 Prev도 1차원 배열의 관점에서 충분히 좋은 이름인데요. 실제 게임 월드에서 우리의 Cube는 수직으로 쌓여있으니 `UpperCube`, `LowerCube`는 어떨까요?

2024-05-20 09:30 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Interaction/Cube/CubeRootHandler.cs
> +    private int _childCount;
큐브 컨트롤 시스템에서 이게 바뀔일이 없다는 점은 알지만, 순전히 프로그래밍 관점에서 이 멤버는 적시(適時)에 update되지 않을 위험이 있어보입니다. Start에서 `transform.childCount`에 여러번 접근해야해서 introduce해야하는 이유는 이해가 갑니다만, local variable로 처리해도 좋겠습니다. 이외 `SelectXXXCube` 함수에서는 `transform.childCount`로 접근해도 됩니다.

2024-05-20 09:30 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Interaction/Cube/CubeRootHandler.cs
> +    private List<Transform> _cubeList = new();
이런 List에는 되도록 `readonly` 키워드를 붙여두도록 합시다.

2024-05-20 13:17 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Easing/EasingFunctions.cs
위치 변경하였습니다.

2024-05-20 13:18 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Interaction/Cube/CubeRootHandler.cs
> +            float duration = EasingFunctions.EaseInOutBounce(alpha);
수정 완료하였습니다.

2024-05-20 13:18 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Interaction/Cube/CubeRootHandler.cs
> +    private int _childCount;
해당 부분 `Start()` 내에서는 local variable로 처리하였고, 이외에는 `transform.childCount`로 접근하도록 수정하였습니다.

2024-05-20 13:18 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Interaction/Cube/CubeRootHandler.cs
> +    private List<Transform> _cubeList = new();
확인했습니다.

2024-05-21 01:57 UTC, hwi-middle approved these changes
LGTM, 수고하셨습니다.

2024-05-21 01:57 UTC, merged