[#43] 일시정지 및 옵션 창 띄우기
hwi-middle/2024-CKGraduationWork pull request #48
Opened 2024-03-25 15:57 UTC by thejae-u

- 옵션 창을 프리팹화 하였습니다.
- 메인 메뉴와 데모 플레이 씬에서 `Esc` 키를 누르면 `TimeScale`을 조절하여 게임을 일시정시 시키고 옵션 창을 띄우도록 하였습니다.
- 옵션 창에서 `Cursor`를 사용 할 수 있도록 로직을 추가하였습니다.
- `IA_Player`에 `Escape Key` 를 추가하였습니다.

2024-03-26 08:27 UTC, hwi-middle commented
구현 내용의 보충이 필요합니다.
- 그래픽 설정에서 해상도 설정 후 닫으면 해당 설정값이 유지되어야함

2024-03-27 13:16 UTC, hwi-middle requested changes
Good. 네이밍 이슈가 있어서 Requst changes로 review 마치고요. 인게임에서 ESC 키 눌러도 OnPause가 호출되지 않는데 이 부분 확인바랍니다.

2024-03-27 13:16 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Utils/SceneManagerBase.cs
> +        if (SceneManager.GetActiveScene().name == "MainMenu")
Scene의 이름을 리터럴로 지정하여 예외처리하는 것은 좋지 않습니다. 차라리 필드로 빼서 커서를 lock할지 여부를 Inspector에서 지정하도록 하는 편이 좋겠습니다.

2024-03-27 13:16 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Utils/SceneManagerBase.cs
> +    private void UpdateSettingSceneEnable()
`ToggleSettingsCanvas`같은 이름을 제안드립니다.

2024-03-27 13:16 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Utils/SceneManagerBase.cs
> +    private void UpdateCursorVisible()
이것도 `Toggle`의 느낌이 강합니다.

2024-03-28 07:00 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Utils/SceneManagerBase.cs
> +    private void UpdateCursorVisible()
변경하였습니다.

2024-03-28 07:00 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Utils/SceneManagerBase.cs
> +        if (SceneManager.GetActiveScene().name == "MainMenu")
`SceneMangerBase`에 `bool` 필드로 처리하겠습니다.

2024-03-28 07:06 UTC, hwi-middle approved these changes

2024-03-28 07:08 UTC, merged