04 tps move
hwi-middle/2024-CKGraduationWork pull request #5
Opened 2024-02-14 08:53 UTC by thejae-u

TPS 및 이동에 대해 구현 하였습니다

resolved #4

2024-02-14 10:03 UTC, hwi-middle requested changes
첫 PR을 환영합니다🎉
전반적으로 우리 팀의 코딩 철학에 잘 맞는 스타일이라 인상깊었습니다. 몇 가지 수정사항이 있어 `Request changes`상태로 review를 마칩니다. 수고많으셨습니다!

2024-02-14 11:23 UTC, thejae-u commented
review 해주신 방식으로 모두 변경 완료하였습니다

2024-02-14 23:41 UTC, hwi-middle requested changes
Request changes로 리뷰 마칩니다. 수고하셨어요. 특히 `CanJump`를 프로퍼티로 구현하신 부분은 인상깊었습니다!

2024-02-14 23:41 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Player/PlayerMovement.cs
> +        private static readonly float RAY_DISTANCE = 1f;
이런 값들은 웬만하면 [SerializeField] private로 빼는게 좋겠습니다.

2024-02-14 23:41 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Player/PlayerMovement.cs
> +        }
이 부분을 프로퍼티로 처리하신 것은 아주 좋습니다. 추후에 필요에 따라 `IsGrounded` 같은 이름으로 변경될 수도 있겠다는 생각도 드네요(지금 수정하라는 의미는 아닙니다).

2024-02-14 23:41 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Player/PlayerMovement.cs
> +            if (_moveDirection == Vector3.zero || !CanJump)
여기서 `!CanJump`라는 조건이 추가된 이유가 뭘까요? 직접 플레이해보니 공중에서는 이동이 아예 안돼서 답답하긴 하네요. 공중에서도 자유롭게 조작이 되는게 이상해서 막으려는 의도였다면 공중에서 제어가능한 정도를 0~1로 정의한 실수 `airControl`같은 변수를 만들어서 `float finalSpeed = _moveSpeed * (CanJump ? airControl : 1f);` 처럼 작성해도 괜찮을 것 같습니다.

2024-02-14 23:41 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Player/PlayerMovement.cs
> +            if (_moveDirection == Vector3.zero || !CanJump)
당장 그렇게 하라는건 아니고, 이번에는 의도만 설명해주시면 감사하겠습니다 ^.^

2024-02-14 23:43 UTC, hwi-middle commented
+) PR 제목도 예쁘게 수정해주세요. 기본적으로는 제목을 자동으로 브랜치 이름에서 따와서 명확하지 않습니다. 이번에는 제가 수정했습니다 ^0^

2024-02-15 14:15 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Player/PlayerMovement.cs
> +            if (_moveDirection == Vector3.zero || !CanJump)
`!CanJump`의 의도는 점프 도중 벽으로 이동하게 되면 벽에 닿은 채로 떨어지지 않는 오류가 발생하여 일단 공중에서는 움직임을 제한하는 방식으로 오류를 수정하였습니다.
오류 수정과 동시에 공중에서 이동이 가능한 방법을 연구 해 보도록 하겠습니다.

2024-02-15 16:04 UTC, thejae-u commented
먼저 꼼꼼한 Review 감사드립니다
기초부터 탄탄하게 라는 느낌으로 언급 해 주신 문제들을 수정 해 보았습니다.

#### 프로퍼티 명 변경
- 기존 `CanJump`에서 `IsGround` 로 수정하였습니다.

 #### 점프 중 이동
- *이제 점프 중 이동이 가능합니다.*
* **수정 내용 간단 설명**
   * `IsWall` 이라는 프로퍼티를 추가하였습니다.
   * 입력 방향과 진행방향에 Ray를 쏴서 벽을 감지합니다.
   * Ray에 감지된 것이 있다면 x, z에 대한 velocity 를 0으로 제한합니다.
   * 필요에 의해 `Update()` 내부에 있던 `finalMoveDirection`을 밖으로 빼게 되었습니다.
 
개인적으로 성능 상의 문제나 또 다른 버그가 발생 할 것 같은 찝찝한 느낌이 있습니다.
문제 혹은 개선 사항이 있다면 말씀 부탁 드리겠습니다..!

2024-02-16 16:24 UTC, hwi-middle approved these changes
네, 일단 벽과 충돌 문제는 추후 별도 Issue로 작업하기로 합시다. Approve로 review 마칩니다. 수고하셨습니다!

2024-02-16 16:24 UTC, merged