[#58] PC 더미 애니 적용
hwi-middle/2024-CKGraduationWork pull request #59
Opened 2024-03-30 14:22 UTC by thejae-u

### 구현 내용
- PC에 `Unity-Chan`을 이용하여 더미로 애니메이션을 적용하였습니다.
- PC 상태에 따라 애니메이션이 전환 됩니다.

### 참고 사항
- 현재 적용 된 애니메이션은 임시 애니메이션으로 테스트 상 애니메이션의 속도와 같은 부분이 안맞을 수 있습니다.
- 영상에는 없지만 슬라이딩 애니메이션도 포함되어있습니다.

https://github.com/hwi-middle/2024-CKGraduationWork/assets/31125543/28d20605-4df8-43a6-9c84-b6658d4c2b71

2024-03-31 11:09 UTC, hwi-middle requested changes
수고하셨습니다~!

2024-03-31 11:09 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Player/AnimationUpdateHelper.cs
> +public class AnimationUpdateHelper : MonoBehaviour
`Helper`라는 이름이 조금 애매합니다.
대안: `AnimationUpdater`, `AnimationHandler`...

2024-03-31 11:09 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Player/AnimationStates.cs
> +public class AnimationStates : MonoBehaviour
플레이어의 애니메이션 `State`라는 것이 명확해야할 것 같습니다.

2024-03-31 11:09 UTC, hwi-middle commented on Assets/_MyAssets/Scripts/Player/PlayerMove.cs
> +        EPlayerState state = 0;
이 부분을 보니 State들을 한 칸씩 shift한 의도를 이해했습니다. 다만, EPlayerState.None 같은 값을 0으로 만들어두고 대입하는게 좋을 것 같습니다.

2024-03-31 11:22 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Player/AnimationUpdateHelper.cs
> +public class AnimationUpdateHelper : MonoBehaviour
`AnimationUpdater` 로 변경하였습니다.

2024-03-31 11:22 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Player/PlayerMove.cs
> +        EPlayerState state = 0;
enum 에 `None`을 추가하여 0으로 취급하도록 수정하였습니다.

2024-03-31 11:22 UTC, thejae-u commented on Assets/_MyAssets/Scripts/Player/AnimationStates.cs
> +public class AnimationStates : MonoBehaviour
`AnimationStates` 앞에 `Player`를 붙여 플레이어의 애니메이션이라는 의미를 명확하게 하도록 하였습니다.

2024-04-01 03:54 UTC, hwi-middle approved these changes

2024-04-01 03:54 UTC, hwi-middle commented
수고 많으셨습니다 ^.^

2024-04-01 03:54 UTC, merged